#!/usr/bin/env node
// export-data.js — single source of truth → RN data export.
// Reads sfis_ingredients.db and writes ../sfis-app/src/data/allergens.json
// (the shape the production matcher consumes: { version, note, terms, opaque, parents }).
//
// Usage:  node database/export-data.js
// Requires the sqlite3 CLI (PATH, or $SQLITE, or the Android platform-tools copy).
// This script is the ONLY sanctioned way to regenerate the export — never hand-edit
// allergens.json (that's what caused the cheese/butter/cream DB↔JSON drift).

const { execFileSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const DB = path.join(__dirname, 'sfis_ingredients.db');
const OUT = path.join(__dirname, '..', 'sfis-app', 'src', 'data', 'allergens.json');

function findSqlite() {
  const candidates = [
    process.env.SQLITE,
    'sqlite3',
    path.join(process.env.HOME || '', 'Library/Android/sdk/platform-tools/sqlite3'),
    '/usr/bin/sqlite3', '/opt/homebrew/bin/sqlite3',
  ].filter(Boolean);
  for (const c of candidates) {
    try { execFileSync(c, ['--version'], { stdio: 'ignore' }); return c; } catch (e) { /* next */ }
  }
  throw new Error('sqlite3 CLI not found. Set $SQLITE to its path.');
}
const SQLITE = findSqlite();
const q = (sql) => JSON.parse(execFileSync(SQLITE, ['-json', DB, sql], { encoding: 'utf8' }) || '[]');

const CAT = { ALLERGEN: 'allergen', INTOLERANCE: 'intolerance', DIETARY_PREFERENCE: 'dietary', GOAL: 'goal' };

const synRows = q(`SELECT s.normalized_term AS term, s.term AS display, s.parent_id AS parent,
    p.common_name AS parentCommon, p.domain AS domain,
    COALESCE(s.match_class,'DERIVED') AS matchClass, s.cross_note AS note
  FROM synonyms s JOIN parents p ON p.parent_id = s.parent_id
  ORDER BY p.domain, s.parent_id, s.term;`);

const parentRows = q(`SELECT parent_id AS id, common_name AS common, domain FROM parents ORDER BY domain, parent_id;`);
const opaqueRows = q(`SELECT DISTINCT normalized_term AS term FROM opaque_terms WHERE normalized_term IS NOT NULL ORDER BY term;`);

const terms = synRows.map((r) => ({
  term: r.term, display: r.display, parent: r.parent, parentCommon: r.parentCommon,
  cat: CAT[r.domain] || 'allergen', matchClass: r.matchClass, note: r.note || null,
}));
const parents = {};
parentRows.forEach((r) => { parents[r.id] = { common: r.common, cat: CAT[r.domain] || 'allergen' }; });
const opaque = opaqueRows.map((r) => r.term);

const out = {
  version: '2026.06-draft',
  note: 'DRAFT data — not validated; prototype only. Generated by database/export-data.js — do not hand-edit.',
  terms, opaque, parents,
};
fs.writeFileSync(OUT, JSON.stringify(out, null, 2) + '\n');
console.log(`wrote ${OUT}\n  terms=${terms.length}  parents=${Object.keys(parents).length}  opaque=${opaque.length}  (sqlite: ${SQLITE})`);
