window.SFIS_DATA = {
  parents: [{"id":"lactose","common":"Lactose","domain":"INTOLERANCE","sub":"intol.lactose","major":0},
{"id":"gluten","common":"Gluten","domain":"INTOLERANCE","sub":"intol.gluten","major":0},
{"id":"fructose","common":"Fructose","domain":"INTOLERANCE","sub":"intol.fructose","major":0},
{"id":"histamine","common":"Histamine","domain":"INTOLERANCE","sub":"intol.histamine","major":0},
{"id":"sulfites","common":"Sulfites","domain":"INTOLERANCE","sub":"intol.sulfites","major":0},
{"id":"caffeine","common":"Caffeine","domain":"INTOLERANCE","sub":"intol.caffeine","major":0},
{"id":"sweeteners","common":"Artificial Sweeteners","domain":"INTOLERANCE","sub":"intol.sweeteners","major":0},
{"id":"fodmaps","common":"FODMAPs","domain":"INTOLERANCE","sub":"intol.fodmaps","major":0},
{"id":"milk","common":"Milk and Dairy","domain":"ALLERGEN","sub":"allergen.milk","major":1},
{"id":"egg","common":"Eggs","domain":"ALLERGEN","sub":"allergen.egg","major":1},
{"id":"wheat","common":"Wheat","domain":"ALLERGEN","sub":"allergen.wheat","major":1},
{"id":"soy","common":"Soybeans","domain":"ALLERGEN","sub":"allergen.soy","major":1},
{"id":"peanut","common":"Peanuts","domain":"ALLERGEN","sub":"allergen.peanut","major":1},
{"id":"fish","common":"Fish","domain":"ALLERGEN","sub":"allergen.fish","major":1},
{"id":"sesame","common":"Sesame","domain":"ALLERGEN","sub":"allergen.sesame","major":1},
{"id":"almond","common":"Almond","domain":"ALLERGEN","sub":"allergen.treenut","major":1},
{"id":"walnut","common":"Walnut","domain":"ALLERGEN","sub":"allergen.treenut","major":1},
{"id":"cashew","common":"Cashew","domain":"ALLERGEN","sub":"allergen.treenut","major":1},
{"id":"pecan","common":"Pecan","domain":"ALLERGEN","sub":"allergen.treenut","major":1},
{"id":"pistachio","common":"Pistachio","domain":"ALLERGEN","sub":"allergen.treenut","major":1},
{"id":"hazelnut","common":"Hazelnut","domain":"ALLERGEN","sub":"allergen.treenut","major":1},
{"id":"brazil_nut","common":"Brazil Nut","domain":"ALLERGEN","sub":"allergen.treenut","major":1},
{"id":"macadamia","common":"Macadamia","domain":"ALLERGEN","sub":"allergen.treenut","major":1},
{"id":"pine_nut","common":"Pine Nut","domain":"ALLERGEN","sub":"allergen.treenut","major":1},
{"id":"crustacean","common":"Crustacean Shellfish","domain":"ALLERGEN","sub":"allergen.shellfish","major":1},
{"id":"mollusc","common":"Mollusc Shellfish","domain":"ALLERGEN","sub":"allergen.shellfish","major":0}],
  synonyms: [{"parent":"milk","term":"Casein","norm":"casein","kind":"contains","note":null},
{"parent":"milk","term":"Caseinate","norm":"caseinate","kind":"contains","note":null},
{"parent":"milk","term":"Sodium caseinate","norm":"sodium caseinate","kind":"contains","note":null},
{"parent":"milk","term":"Calcium caseinate","norm":"calcium caseinate","kind":"contains","note":null},
{"parent":"milk","term":"Potassium caseinate","norm":"potassium caseinate","kind":"contains","note":null},
{"parent":"milk","term":"Rennet casein","norm":"rennet casein","kind":"contains","note":null},
{"parent":"milk","term":"Whey","norm":"whey","kind":"contains","note":null},
{"parent":"milk","term":"Whey protein concentrate","norm":"whey protein concentrate","kind":"contains","note":null},
{"parent":"milk","term":"Whey protein isolate","norm":"whey protein isolate","kind":"contains","note":null},
{"parent":"milk","term":"Lactalbumin","norm":"lactalbumin","kind":"contains","note":null},
{"parent":"milk","term":"Lactoglobulin","norm":"lactoglobulin","kind":"contains","note":null},
{"parent":"milk","term":"Lactoferrin","norm":"lactoferrin","kind":"contains","note":null},
{"parent":"milk","term":"Lactose","norm":"lactose","kind":"may","note":"Pure lactose is a milk SUGAR; may carry trace milk protein depending on manufacture. Also an intolerance parent."},
{"parent":"milk","term":"Milk solids","norm":"milk solids","kind":"contains","note":null},
{"parent":"milk","term":"Nonfat milk solids","norm":"nonfat milk solids","kind":"contains","note":null},
{"parent":"milk","term":"Milk powder","norm":"milk powder","kind":"contains","note":null},
{"parent":"milk","term":"Dry milk","norm":"dry milk","kind":"contains","note":null},
{"parent":"milk","term":"Buttermilk","norm":"buttermilk","kind":"contains","note":null},
{"parent":"milk","term":"Butterfat","norm":"butterfat","kind":"contains","note":null},
{"parent":"milk","term":"Ghee","norm":"ghee","kind":"contains","note":null},
{"parent":"milk","term":"Curds","norm":"curds","kind":"contains","note":null},
{"parent":"milk","term":"Milk protein","norm":"milk protein","kind":"contains","note":null},
{"parent":"milk","term":"Hydrolyzed casein","norm":"hydrolyzed casein","kind":"contains","note":null},
{"parent":"milk","term":"Recaldent","norm":"recaldent","kind":"may","note":"CPP-ACP; milk-derived ingredient in some dental/gum products"},
{"parent":"milk","term":"Natural flavoring","norm":"natural flavoring","kind":"may","note":"May be milk-derived; verify with manufacturer"},
{"parent":"egg","term":"Albumin","norm":"albumin","kind":"contains","note":null},
{"parent":"egg","term":"Albumen","norm":"albumen","kind":"contains","note":null},
{"parent":"egg","term":"Ovalbumin","norm":"ovalbumin","kind":"contains","note":null},
{"parent":"egg","term":"Ovomucoid","norm":"ovomucoid","kind":"contains","note":null},
{"parent":"egg","term":"Ovomucin","norm":"ovomucin","kind":"contains","note":null},
{"parent":"egg","term":"Ovotransferrin","norm":"ovotransferrin","kind":"contains","note":null},
{"parent":"egg","term":"Conalbumin","norm":"conalbumin","kind":"contains","note":null},
{"parent":"egg","term":"Livetin","norm":"livetin","kind":"contains","note":null},
{"parent":"egg","term":"Lysozyme","norm":"lysozyme","kind":"contains","note":null},
{"parent":"egg","term":"Globulin","norm":"globulin","kind":"may","note":"Egg protein fraction; confirm context"},
{"parent":"egg","term":"Vitellin","norm":"vitellin","kind":"contains","note":null},
{"parent":"egg","term":"Ovovitellin","norm":"ovovitellin","kind":"contains","note":null},
{"parent":"egg","term":"Meringue","norm":"meringue","kind":"contains","note":null},
{"parent":"egg","term":"Mayonnaise","norm":"mayonnaise","kind":"contains","note":null},
{"parent":"egg","term":"Egg white","norm":"egg white","kind":"contains","note":null},
{"parent":"egg","term":"Egg yolk","norm":"egg yolk","kind":"contains","note":null},
{"parent":"egg","term":"Dried egg","norm":"dried egg","kind":"contains","note":null},
{"parent":"egg","term":"Egg powder","norm":"egg powder","kind":"contains","note":null},
{"parent":"egg","term":"Egg solids","norm":"egg solids","kind":"contains","note":null},
{"parent":"egg","term":"Lecithin","norm":"lecithin","kind":"may","note":"Usually soy-derived; can be egg-derived (E322) — dual-source, verify"},
{"parent":"egg","term":"Surimi","norm":"surimi","kind":"may","note":"Often contains egg white as binder; also a fish product"},
{"parent":"wheat","term":"Wheat flour","norm":"wheat flour","kind":"contains","note":null},
{"parent":"wheat","term":"Whole wheat","norm":"whole wheat","kind":"contains","note":null},
{"parent":"wheat","term":"Semolina","norm":"semolina","kind":"contains","note":null},
{"parent":"wheat","term":"Durum","norm":"durum","kind":"contains","note":null},
{"parent":"wheat","term":"Durum wheat","norm":"durum wheat","kind":"contains","note":null},
{"parent":"wheat","term":"Spelt","norm":"spelt","kind":"contains","note":null},
{"parent":"wheat","term":"Farina","norm":"farina","kind":"contains","note":null},
{"parent":"wheat","term":"Einkorn","norm":"einkorn","kind":"contains","note":null},
{"parent":"wheat","term":"Emmer","norm":"emmer","kind":"contains","note":null},
{"parent":"wheat","term":"Kamut","norm":"kamut","kind":"contains","note":null},
{"parent":"wheat","term":"Khorasan wheat","norm":"khorasan wheat","kind":"contains","note":null},
{"parent":"wheat","term":"Farro","norm":"farro","kind":"contains","note":null},
{"parent":"wheat","term":"Bulgur","norm":"bulgur","kind":"contains","note":null},
{"parent":"wheat","term":"Couscous","norm":"couscous","kind":"contains","note":null},
{"parent":"wheat","term":"Seitan","norm":"seitan","kind":"contains","note":null},
{"parent":"wheat","term":"Vital wheat gluten","norm":"vital wheat gluten","kind":"contains","note":null},
{"parent":"wheat","term":"Wheat gluten","norm":"wheat gluten","kind":"contains","note":null},
{"parent":"wheat","term":"Wheat starch","norm":"wheat starch","kind":"may","note":"Processing-dependent: Codex gluten-free wheat starch exists; protein/gluten content varies. Confirm context."},
{"parent":"wheat","term":"Wheat bran","norm":"wheat bran","kind":"contains","note":null},
{"parent":"wheat","term":"Wheat germ","norm":"wheat germ","kind":"contains","note":null},
{"parent":"wheat","term":"Hydrolyzed wheat protein","norm":"hydrolyzed wheat protein","kind":"contains","note":null},
{"parent":"wheat","term":"Modified wheat starch","norm":"modified wheat starch","kind":"may","note":"Processing-dependent; protein/gluten content varies. Confirm context."},
{"parent":"wheat","term":"Atta flour","norm":"atta flour","kind":"contains","note":null},
{"parent":"wheat","term":"Graham flour","norm":"graham flour","kind":"contains","note":null},
{"parent":"wheat","term":"Matzo","norm":"matzo","kind":"contains","note":null},
{"parent":"wheat","term":"Triticale","norm":"triticale","kind":"may","note":"Wheat-rye hybrid; relevant to wheat-avoiders"},
{"parent":"soy","term":"Soya","norm":"soya","kind":"contains","note":null},
{"parent":"soy","term":"Soybean","norm":"soybean","kind":"contains","note":null},
{"parent":"soy","term":"Edamame","norm":"edamame","kind":"contains","note":null},
{"parent":"soy","term":"Tofu","norm":"tofu","kind":"contains","note":null},
{"parent":"soy","term":"Tempeh","norm":"tempeh","kind":"contains","note":null},
{"parent":"soy","term":"Miso","norm":"miso","kind":"contains","note":null},
{"parent":"soy","term":"Natto","norm":"natto","kind":"contains","note":null},
{"parent":"soy","term":"Soy protein","norm":"soy protein","kind":"contains","note":null},
{"parent":"soy","term":"Soy protein isolate","norm":"soy protein isolate","kind":"contains","note":null},
{"parent":"soy","term":"Soy protein concentrate","norm":"soy protein concentrate","kind":"contains","note":null},
{"parent":"soy","term":"Textured vegetable protein","norm":"textured vegetable protein","kind":"contains","note":null},
{"parent":"soy","term":"TVP","norm":"tvp","kind":"contains","note":null},
{"parent":"soy","term":"Tamari","norm":"tamari","kind":"contains","note":null},
{"parent":"soy","term":"Soy sauce","norm":"soy sauce","kind":"contains","note":"Usually also contains wheat — flag wheat too"},
{"parent":"soy","term":"Soy flour","norm":"soy flour","kind":"contains","note":null},
{"parent":"soy","term":"Hydrolyzed soy protein","norm":"hydrolyzed soy protein","kind":"contains","note":null},
{"parent":"soy","term":"Okara","norm":"okara","kind":"contains","note":null},
{"parent":"soy","term":"Yuba","norm":"yuba","kind":"contains","note":null},
{"parent":"soy","term":"Soy lecithin","norm":"soy lecithin","kind":"may","note":"Soy-derived emulsifier (E322); many soy-allergic tolerate it"},
{"parent":"soy","term":"Soybean oil","norm":"soybean oil","kind":"may","note":"Highly refined oil often tolerated; cold-pressed may carry protein"},
{"parent":"peanut","term":"Arachis oil","norm":"arachis oil","kind":"may","note":"Highly refined peanut oil is exempt from major-allergen labeling (statute targets allergenic protein); unrefined/cold-/expeller-pressed retains protein."},
{"parent":"peanut","term":"Arachis hypogaea","norm":"arachis hypogaea","kind":"contains","note":null},
{"parent":"peanut","term":"Groundnut","norm":"groundnut","kind":"contains","note":null},
{"parent":"peanut","term":"Groundnut oil","norm":"groundnut oil","kind":"may","note":"Refined groundnut oil is protein-exempt; unrefined retains protein."},
{"parent":"peanut","term":"Cold-pressed peanut oil","norm":"cold-pressed peanut oil","kind":"contains","note":"Unrefined — retains allergenic protein; not exempt."},
{"parent":"peanut","term":"Expeller-pressed peanut oil","norm":"expeller-pressed peanut oil","kind":"contains","note":"Unrefined — retains allergenic protein; not exempt."},
{"parent":"peanut","term":"Monkey nut","norm":"monkey nut","kind":"contains","note":null},
{"parent":"peanut","term":"Beer nuts","norm":"beer nuts","kind":"contains","note":null},
{"parent":"peanut","term":"Mandelona","norm":"mandelona","kind":"contains","note":"Peanuts flavored to imitate almonds"},
{"parent":"peanut","term":"Goober","norm":"goober","kind":"contains","note":null},
{"parent":"peanut","term":"Goober peas","norm":"goober peas","kind":"contains","note":null},
{"parent":"peanut","term":"Peanut butter","norm":"peanut butter","kind":"contains","note":null},
{"parent":"peanut","term":"Peanut flour","norm":"peanut flour","kind":"contains","note":null},
{"parent":"peanut","term":"Peanut protein","norm":"peanut protein","kind":"contains","note":null},
{"parent":"peanut","term":"Hydrolyzed peanut protein","norm":"hydrolyzed peanut protein","kind":"contains","note":null},
{"parent":"peanut","term":"Valencia peanut","norm":"valencia peanut","kind":"contains","note":null},
{"parent":"almond","term":"Almond oil","norm":"almond oil","kind":"may","note":"Refined almond oil is largely protein-exempt; unrefined/cold-pressed retains protein."},
{"parent":"almond","term":"Almond butter","norm":"almond butter","kind":"contains","note":null},
{"parent":"almond","term":"Almond flour","norm":"almond flour","kind":"contains","note":null},
{"parent":"almond","term":"Almond paste","norm":"almond paste","kind":"contains","note":null},
{"parent":"almond","term":"Marzipan","norm":"marzipan","kind":"contains","note":null},
{"parent":"almond","term":"Almond extract","norm":"almond extract","kind":"may","note":"May be imitation/benzaldehyde; verify if true almond"},
{"parent":"almond","term":"Praline","norm":"praline","kind":"may","note":"Typically almond or hazelnut — verify nut"},
{"parent":"walnut","term":"Walnut oil","norm":"walnut oil","kind":"may","note":"Refined walnut oil is largely protein-exempt; unrefined/cold-pressed retains protein."},
{"parent":"walnut","term":"Black walnut","norm":"black walnut","kind":"contains","note":"FDA-named walnut type."},
{"parent":"walnut","term":"California walnut","norm":"california walnut","kind":"contains","note":"FDA-named walnut type (English/Persian)."},
{"parent":"walnut","term":"English walnut","norm":"english walnut","kind":"contains","note":"FDA-named walnut type (Persian)."},
{"parent":"walnut","term":"Persian walnut","norm":"persian walnut","kind":"contains","note":"FDA-named walnut type (English)."},
{"parent":"walnut","term":"Heartnut","norm":"heartnut","kind":"contains","note":"Japanese walnut; FDA-named walnut type."},
{"parent":"walnut","term":"Japanese walnut","norm":"japanese walnut","kind":"contains","note":"Heartnut; FDA-named walnut type."},
{"parent":"cashew","term":"Cashew butter","norm":"cashew butter","kind":"contains","note":null},
{"parent":"hazelnut","term":"Filbert","norm":"filbert","kind":"contains","note":null},
{"parent":"hazelnut","term":"Gianduja","norm":"gianduja","kind":"contains","note":"Chocolate-hazelnut paste"},
{"parent":"hazelnut","term":"Frangelico","norm":"frangelico","kind":"may","note":"Hazelnut liqueur"},
{"parent":"brazil_nut","term":"Brazil nut","norm":"brazil nut","kind":"contains","note":null},
{"parent":"macadamia","term":"Macadamia nut","norm":"macadamia nut","kind":"contains","note":null},
{"parent":"macadamia","term":"Queensland nut","norm":"queensland nut","kind":"contains","note":null},
{"parent":"macadamia","term":"Bush nut","norm":"bush nut","kind":"contains","note":null},
{"parent":"pine_nut","term":"Pignoli","norm":"pignoli","kind":"contains","note":null},
{"parent":"pine_nut","term":"Pinon","norm":"pinon","kind":"contains","note":null},
{"parent":"fish","term":"Anchovy","norm":"anchovy","kind":"contains","note":null},
{"parent":"fish","term":"Cod","norm":"cod","kind":"contains","note":null},
{"parent":"fish","term":"Salmon","norm":"salmon","kind":"contains","note":null},
{"parent":"fish","term":"Tuna","norm":"tuna","kind":"contains","note":null},
{"parent":"fish","term":"Tilapia","norm":"tilapia","kind":"contains","note":null},
{"parent":"fish","term":"Bass","norm":"bass","kind":"contains","note":null},
{"parent":"fish","term":"Haddock","norm":"haddock","kind":"contains","note":null},
{"parent":"fish","term":"Halibut","norm":"halibut","kind":"contains","note":null},
{"parent":"fish","term":"Mackerel","norm":"mackerel","kind":"contains","note":null},
{"parent":"fish","term":"Sardine","norm":"sardine","kind":"contains","note":null},
{"parent":"fish","term":"Herring","norm":"herring","kind":"contains","note":null},
{"parent":"fish","term":"Trout","norm":"trout","kind":"contains","note":null},
{"parent":"fish","term":"Pollock","norm":"pollock","kind":"contains","note":null},
{"parent":"fish","term":"Surimi","norm":"surimi","kind":"contains","note":"Imitation crab made from fish"},
{"parent":"fish","term":"Fish sauce","norm":"fish sauce","kind":"contains","note":null},
{"parent":"fish","term":"Fish gelatin","norm":"fish gelatin","kind":"contains","note":null},
{"parent":"fish","term":"Fish stock","norm":"fish stock","kind":"contains","note":null},
{"parent":"fish","term":"Caviar","norm":"caviar","kind":"contains","note":null},
{"parent":"fish","term":"Roe","norm":"roe","kind":"contains","note":null},
{"parent":"fish","term":"Fish oil","norm":"fish oil","kind":"may","note":"Refined fish oil may retain trace protein"},
{"parent":"fish","term":"Worcestershire sauce","norm":"worcestershire sauce","kind":"may","note":"Often contains anchovy"},
{"parent":"fish","term":"Omega-3","norm":"omega-3","kind":"may","note":"May be fish-derived; can be algal/plant — verify source"},
{"parent":"crustacean","term":"Shrimp","norm":"shrimp","kind":"contains","note":null},
{"parent":"crustacean","term":"Prawn","norm":"prawn","kind":"contains","note":null},
{"parent":"crustacean","term":"Crab","norm":"crab","kind":"contains","note":null},
{"parent":"crustacean","term":"Lobster","norm":"lobster","kind":"contains","note":null},
{"parent":"crustacean","term":"Crayfish","norm":"crayfish","kind":"contains","note":null},
{"parent":"crustacean","term":"Crawfish","norm":"crawfish","kind":"contains","note":null},
{"parent":"crustacean","term":"Langoustine","norm":"langoustine","kind":"contains","note":null},
{"parent":"crustacean","term":"Krill","norm":"krill","kind":"contains","note":null},
{"parent":"crustacean","term":"Scampi","norm":"scampi","kind":"contains","note":null},
{"parent":"mollusc","term":"Clam","norm":"clam","kind":"contains","note":null},
{"parent":"mollusc","term":"Mussel","norm":"mussel","kind":"contains","note":null},
{"parent":"mollusc","term":"Oyster","norm":"oyster","kind":"contains","note":null},
{"parent":"mollusc","term":"Scallop","norm":"scallop","kind":"contains","note":null},
{"parent":"mollusc","term":"Squid","norm":"squid","kind":"contains","note":null},
{"parent":"mollusc","term":"Calamari","norm":"calamari","kind":"contains","note":null},
{"parent":"mollusc","term":"Octopus","norm":"octopus","kind":"contains","note":null},
{"parent":"mollusc","term":"Snail","norm":"snail","kind":"contains","note":null},
{"parent":"mollusc","term":"Escargot","norm":"escargot","kind":"contains","note":null},
{"parent":"mollusc","term":"Abalone","norm":"abalone","kind":"contains","note":null},
{"parent":"mollusc","term":"Cockle","norm":"cockle","kind":"contains","note":null},
{"parent":"mollusc","term":"Whelk","norm":"whelk","kind":"contains","note":null},
{"parent":"mollusc","term":"Cuttlefish","norm":"cuttlefish","kind":"contains","note":null},
{"parent":"mollusc","term":"Glucosamine","norm":"glucosamine","kind":"may","note":"Often shellfish-derived; can be corn-fermented — verify source"},
{"parent":"sesame","term":"Sesame seed","norm":"sesame seed","kind":"contains","note":null},
{"parent":"sesame","term":"Sesame oil","norm":"sesame oil","kind":"may","note":"Refined sesame oil is largely protein-exempt; culinary/toasted sesame oil is usually unrefined and retains protein."},
{"parent":"sesame","term":"Toasted sesame oil","norm":"toasted sesame oil","kind":"contains","note":"Unrefined/aromatic — retains protein; not exempt."},
{"parent":"sesame","term":"Sesame paste","norm":"sesame paste","kind":"contains","note":null},
{"parent":"sesame","term":"Tahini","norm":"tahini","kind":"contains","note":null},
{"parent":"sesame","term":"Tahina","norm":"tahina","kind":"contains","note":null},
{"parent":"sesame","term":"Sesamol","norm":"sesamol","kind":"contains","note":null},
{"parent":"sesame","term":"Sesamin","norm":"sesamin","kind":"contains","note":null},
{"parent":"sesame","term":"Benne","norm":"benne","kind":"contains","note":null},
{"parent":"sesame","term":"Benniseed","norm":"benniseed","kind":"contains","note":null},
{"parent":"sesame","term":"Gingelly","norm":"gingelly","kind":"contains","note":null},
{"parent":"sesame","term":"Gingelly oil","norm":"gingelly oil","kind":"may","note":"Refined is largely protein-exempt; unrefined retains protein."},
{"parent":"sesame","term":"Til","norm":"til","kind":"contains","note":null},
{"parent":"sesame","term":"Halvah","norm":"halvah","kind":"contains","note":null},
{"parent":"sesame","term":"Sim sim","norm":"sim sim","kind":"contains","note":null},
{"parent":"sesame","term":"Sesame flour","norm":"sesame flour","kind":"contains","note":null},
{"parent":"sesame","term":"Hummus","norm":"hummus","kind":"may","note":"Usually contains tahini (sesame) but not always; broad term — inference only."},
{"parent":"milk","term":"Milk","norm":"milk","kind":"contains","note":null},
{"parent":"egg","term":"Egg","norm":"egg","kind":"contains","note":null},
{"parent":"egg","term":"Eggs","norm":"eggs","kind":"contains","note":null},
{"parent":"wheat","term":"Wheat","norm":"wheat","kind":"contains","note":null},
{"parent":"soy","term":"Soy","norm":"soy","kind":"contains","note":null},
{"parent":"peanut","term":"Peanut","norm":"peanut","kind":"contains","note":null},
{"parent":"peanut","term":"Peanuts","norm":"peanuts","kind":"contains","note":null},
{"parent":"fish","term":"Fish","norm":"fish","kind":"contains","note":null},
{"parent":"sesame","term":"Sesame","norm":"sesame","kind":"contains","note":null},
{"parent":"almond","term":"Almond","norm":"almond","kind":"contains","note":null},
{"parent":"almond","term":"Almonds","norm":"almonds","kind":"contains","note":null},
{"parent":"walnut","term":"Walnut","norm":"walnut","kind":"contains","note":null},
{"parent":"walnut","term":"Walnuts","norm":"walnuts","kind":"contains","note":null},
{"parent":"cashew","term":"Cashew","norm":"cashew","kind":"contains","note":null},
{"parent":"cashew","term":"Cashews","norm":"cashews","kind":"contains","note":null},
{"parent":"pecan","term":"Pecan","norm":"pecan","kind":"contains","note":null},
{"parent":"pecan","term":"Pecans","norm":"pecans","kind":"contains","note":null},
{"parent":"pistachio","term":"Pistachio","norm":"pistachio","kind":"contains","note":null},
{"parent":"pistachio","term":"Pistachios","norm":"pistachios","kind":"contains","note":null},
{"parent":"hazelnut","term":"Hazelnut","norm":"hazelnut","kind":"contains","note":null},
{"parent":"hazelnut","term":"Hazelnuts","norm":"hazelnuts","kind":"contains","note":null},
{"parent":"brazil_nut","term":"Brazil nuts","norm":"brazil nuts","kind":"contains","note":null},
{"parent":"macadamia","term":"Macadamia","norm":"macadamia","kind":"contains","note":null},
{"parent":"pine_nut","term":"Pine nut","norm":"pine nut","kind":"contains","note":null},
{"parent":"pine_nut","term":"Pine nuts","norm":"pine nuts","kind":"contains","note":null},
{"parent":"pine_nut","term":"Pinon nut","norm":"pinon nut","kind":"contains","note":null},
{"parent":"crustacean","term":"Crustacean","norm":"crustacean","kind":"contains","note":null},
{"parent":"mollusc","term":"Mollusc","norm":"mollusc","kind":"contains","note":null},
{"parent":"mollusc","term":"Mollusk","norm":"mollusk","kind":"contains","note":null},
{"parent":"milk","term":"Cow milk","norm":"cow milk","kind":"contains","note":null},
{"parent":"milk","term":"Goat milk","norm":"goat milk","kind":"contains","note":"FDA 2025: ruminant milk."},
{"parent":"milk","term":"Sheep milk","norm":"sheep milk","kind":"contains","note":"FDA 2025: ruminant milk."},
{"parent":"milk","term":"Buffalo milk","norm":"buffalo milk","kind":"contains","note":"Ruminant milk."},
{"parent":"milk","term":"Goat cheese","norm":"goat cheese","kind":"contains","note":null},
{"parent":"milk","term":"Sheep cheese","norm":"sheep cheese","kind":"contains","note":null},
{"parent":"milk","term":"Goat whey","norm":"goat whey","kind":"contains","note":null},
{"parent":"milk","term":"Pecorino","norm":"pecorino","kind":"contains","note":"Sheep-milk cheese."},
{"parent":"egg","term":"Chicken egg","norm":"chicken egg","kind":"contains","note":null},
{"parent":"egg","term":"Duck egg","norm":"duck egg","kind":"contains","note":"FDA 2025: fowl egg."},
{"parent":"egg","term":"Goose egg","norm":"goose egg","kind":"contains","note":"FDA 2025: fowl egg."},
{"parent":"egg","term":"Quail egg","norm":"quail egg","kind":"contains","note":"FDA 2025: fowl egg."},
{"parent":"egg","term":"Fowl egg","norm":"fowl egg","kind":"contains","note":"FDA 2025: covers other fowl."},
{"parent":"lactose","term":"Lactose","norm":"lactose","kind":"contains","note":null},
{"parent":"lactose","term":"Milk","norm":"milk","kind":"contains","note":null},
{"parent":"lactose","term":"Whole milk","norm":"whole milk","kind":"contains","note":null},
{"parent":"lactose","term":"Skim milk","norm":"skim milk","kind":"contains","note":null},
{"parent":"lactose","term":"Milk solids","norm":"milk solids","kind":"contains","note":null},
{"parent":"lactose","term":"Milk powder","norm":"milk powder","kind":"contains","note":null},
{"parent":"lactose","term":"Buttermilk","norm":"buttermilk","kind":"contains","note":null},
{"parent":"lactose","term":"Cream","norm":"cream","kind":"contains","note":null},
{"parent":"lactose","term":"Condensed milk","norm":"condensed milk","kind":"contains","note":null},
{"parent":"lactose","term":"Evaporated milk","norm":"evaporated milk","kind":"contains","note":null},
{"parent":"lactose","term":"Ice cream","norm":"ice cream","kind":"contains","note":null},
{"parent":"lactose","term":"Lactose monohydrate","norm":"lactose monohydrate","kind":"contains","note":null},
{"parent":"lactose","term":"Curds","norm":"curds","kind":"contains","note":null},
{"parent":"lactose","term":"Whey","norm":"whey","kind":"may","note":"Whey can be low-lactose depending on processing."},
{"parent":"lactose","term":"Cheese","norm":"cheese","kind":"may","note":"Aged/hard cheeses are often very low in lactose."},
{"parent":"lactose","term":"Butter","norm":"butter","kind":"may","note":"Very low lactose."},
{"parent":"gluten","term":"Gluten","norm":"gluten","kind":"contains","note":null},
{"parent":"gluten","term":"Wheat","norm":"wheat","kind":"contains","note":null},
{"parent":"gluten","term":"Barley","norm":"barley","kind":"contains","note":null},
{"parent":"gluten","term":"Rye","norm":"rye","kind":"contains","note":null},
{"parent":"gluten","term":"Triticale","norm":"triticale","kind":"contains","note":null},
{"parent":"gluten","term":"Malt","norm":"malt","kind":"contains","note":"Usually barley-derived."},
{"parent":"gluten","term":"Malt extract","norm":"malt extract","kind":"contains","note":null},
{"parent":"gluten","term":"Malt vinegar","norm":"malt vinegar","kind":"contains","note":null},
{"parent":"gluten","term":"Spelt","norm":"spelt","kind":"contains","note":null},
{"parent":"gluten","term":"Kamut","norm":"kamut","kind":"contains","note":null},
{"parent":"gluten","term":"Semolina","norm":"semolina","kind":"contains","note":null},
{"parent":"gluten","term":"Durum","norm":"durum","kind":"contains","note":null},
{"parent":"gluten","term":"Farro","norm":"farro","kind":"contains","note":null},
{"parent":"gluten","term":"Bulgur","norm":"bulgur","kind":"contains","note":null},
{"parent":"gluten","term":"Seitan","norm":"seitan","kind":"contains","note":null},
{"parent":"gluten","term":"Brewer's yeast","norm":"brewer's yeast","kind":"may","note":"Often barley-derived."},
{"parent":"gluten","term":"Oats","norm":"oats","kind":"may","note":"Pure oats are gluten-free; risk is cross-contamination."},
{"parent":"gluten","term":"Wheat starch","norm":"wheat starch","kind":"may","note":"Codex gluten-free wheat starch exists; varies."},
{"parent":"fructose","term":"Fructose","norm":"fructose","kind":"contains","note":null},
{"parent":"fructose","term":"Crystalline fructose","norm":"crystalline fructose","kind":"contains","note":null},
{"parent":"fructose","term":"High-fructose corn syrup","norm":"high-fructose corn syrup","kind":"contains","note":null},
{"parent":"fructose","term":"HFCS","norm":"hfcs","kind":"contains","note":null},
{"parent":"fructose","term":"Agave","norm":"agave","kind":"contains","note":null},
{"parent":"fructose","term":"Agave nectar","norm":"agave nectar","kind":"contains","note":null},
{"parent":"fructose","term":"Honey","norm":"honey","kind":"contains","note":null},
{"parent":"fructose","term":"Invert sugar","norm":"invert sugar","kind":"may","note":null},
{"parent":"fructose","term":"Fruit juice concentrate","norm":"fruit juice concentrate","kind":"may","note":null},
{"parent":"fructose","term":"Sorbitol","norm":"sorbitol","kind":"may","note":"Polyol; worsens fructose malabsorption."},
{"parent":"fructose","term":"Inulin","norm":"inulin","kind":"may","note":null},
{"parent":"histamine","term":"Aged cheese","norm":"aged cheese","kind":"contains","note":null},
{"parent":"histamine","term":"Cured meats","norm":"cured meats","kind":"contains","note":null},
{"parent":"histamine","term":"Salami","norm":"salami","kind":"contains","note":null},
{"parent":"histamine","term":"Fermented foods","norm":"fermented foods","kind":"contains","note":null},
{"parent":"histamine","term":"Sauerkraut","norm":"sauerkraut","kind":"contains","note":null},
{"parent":"histamine","term":"Kimchi","norm":"kimchi","kind":"contains","note":null},
{"parent":"histamine","term":"Wine","norm":"wine","kind":"contains","note":null},
{"parent":"histamine","term":"Smoked fish","norm":"smoked fish","kind":"contains","note":null},
{"parent":"histamine","term":"Soy sauce","norm":"soy sauce","kind":"may","note":null},
{"parent":"histamine","term":"Vinegar","norm":"vinegar","kind":"may","note":null},
{"parent":"histamine","term":"Tuna","norm":"tuna","kind":"may","note":"Scombroid risk if poorly stored."},
{"parent":"histamine","term":"Tomatoes","norm":"tomatoes","kind":"may","note":"Histamine liberator."},
{"parent":"histamine","term":"Spinach","norm":"spinach","kind":"may","note":null},
{"parent":"histamine","term":"Avocado","norm":"avocado","kind":"may","note":null},
{"parent":"sulfites","term":"Sulfites","norm":"sulfites","kind":"contains","note":null},
{"parent":"sulfites","term":"Sulphur dioxide","norm":"sulphur dioxide","kind":"contains","note":null},
{"parent":"sulfites","term":"Sulfur dioxide","norm":"sulfur dioxide","kind":"contains","note":null},
{"parent":"sulfites","term":"Sodium sulfite","norm":"sodium sulfite","kind":"contains","note":null},
{"parent":"sulfites","term":"Sodium bisulfite","norm":"sodium bisulfite","kind":"contains","note":null},
{"parent":"sulfites","term":"Sodium metabisulfite","norm":"sodium metabisulfite","kind":"contains","note":null},
{"parent":"sulfites","term":"Potassium bisulfite","norm":"potassium bisulfite","kind":"contains","note":null},
{"parent":"sulfites","term":"Potassium metabisulfite","norm":"potassium metabisulfite","kind":"contains","note":null},
{"parent":"sulfites","term":"E220","norm":"e220","kind":"contains","note":"Sulphur dioxide."},
{"parent":"sulfites","term":"E223","norm":"e223","kind":"contains","note":"Sodium metabisulfite."},
{"parent":"sulfites","term":"E224","norm":"e224","kind":"contains","note":"Potassium metabisulfite."},
{"parent":"caffeine","term":"Caffeine","norm":"caffeine","kind":"contains","note":null},
{"parent":"caffeine","term":"Coffee","norm":"coffee","kind":"contains","note":null},
{"parent":"caffeine","term":"Tea","norm":"tea","kind":"contains","note":null},
{"parent":"caffeine","term":"Green tea","norm":"green tea","kind":"contains","note":null},
{"parent":"caffeine","term":"Black tea","norm":"black tea","kind":"contains","note":null},
{"parent":"caffeine","term":"Matcha","norm":"matcha","kind":"contains","note":null},
{"parent":"caffeine","term":"Guarana","norm":"guarana","kind":"contains","note":null},
{"parent":"caffeine","term":"Yerba mate","norm":"yerba mate","kind":"contains","note":null},
{"parent":"caffeine","term":"Kola nut","norm":"kola nut","kind":"contains","note":null},
{"parent":"caffeine","term":"Cocoa","norm":"cocoa","kind":"may","note":"Contains some caffeine + theobromine."},
{"parent":"caffeine","term":"Chocolate","norm":"chocolate","kind":"may","note":null},
{"parent":"caffeine","term":"Green tea extract","norm":"green tea extract","kind":"contains","note":null},
{"parent":"sweeteners","term":"Aspartame","norm":"aspartame","kind":"contains","note":null},
{"parent":"sweeteners","term":"Sucralose","norm":"sucralose","kind":"contains","note":null},
{"parent":"sweeteners","term":"Saccharin","norm":"saccharin","kind":"contains","note":null},
{"parent":"sweeteners","term":"Acesulfame potassium","norm":"acesulfame potassium","kind":"contains","note":null},
{"parent":"sweeteners","term":"Acesulfame K","norm":"acesulfame k","kind":"contains","note":null},
{"parent":"sweeteners","term":"Neotame","norm":"neotame","kind":"contains","note":null},
{"parent":"sweeteners","term":"Advantame","norm":"advantame","kind":"contains","note":null},
{"parent":"sweeteners","term":"E951","norm":"e951","kind":"contains","note":"Aspartame."},
{"parent":"sweeteners","term":"E955","norm":"e955","kind":"contains","note":"Sucralose."},
{"parent":"sweeteners","term":"E950","norm":"e950","kind":"contains","note":"Acesulfame K."},
{"parent":"fodmaps","term":"Fructans","norm":"fructans","kind":"contains","note":null},
{"parent":"fodmaps","term":"Galacto-oligosaccharides","norm":"galacto-oligosaccharides","kind":"contains","note":null},
{"parent":"fodmaps","term":"GOS","norm":"gos","kind":"contains","note":null},
{"parent":"fodmaps","term":"Inulin","norm":"inulin","kind":"contains","note":null},
{"parent":"fodmaps","term":"Chicory root","norm":"chicory root","kind":"contains","note":null},
{"parent":"fodmaps","term":"Sorbitol","norm":"sorbitol","kind":"contains","note":null},
{"parent":"fodmaps","term":"Mannitol","norm":"mannitol","kind":"contains","note":null},
{"parent":"fodmaps","term":"Xylitol","norm":"xylitol","kind":"contains","note":null},
{"parent":"fodmaps","term":"Maltitol","norm":"maltitol","kind":"contains","note":null},
{"parent":"fodmaps","term":"Onion","norm":"onion","kind":"contains","note":null},
{"parent":"fodmaps","term":"Garlic","norm":"garlic","kind":"contains","note":null},
{"parent":"fodmaps","term":"Lactose","norm":"lactose","kind":"may","note":"A FODMAP for those who malabsorb it."},
{"parent":"fodmaps","term":"Wheat","norm":"wheat","kind":"may","note":"Fructan source."},
{"parent":"soy","term":"Lecithin","norm":"lecithin","kind":"may","note":"Most bare \"lecithin\" is soy-derived; can be egg/sunflower (egg edge also modelled)."},
{"parent":"soy","term":"Tocopherols","norm":"tocopherols","kind":"may","note":"Often soy-derived; can be sunflower/other. Verify."},
{"parent":"soy","term":"Vitamin E","norm":"vitamin e","kind":"may","note":"Frequently soy-derived tocopherols."},
{"parent":"soy","term":"Mono- and diglycerides","norm":"mono- and diglycerides","kind":"may","note":"Emulsifier; can be soy-, other-plant-, or animal-derived."},
{"parent":"milk","term":"Mono- and diglycerides","norm":"mono- and diglycerides","kind":"may","note":"Can be animal-fat-derived."},
{"parent":"milk","term":"Enzymes","norm":"enzymes","kind":"may","note":"In cheese/dairy products may carry milk."},
{"parent":"milk","term":"Cultures","norm":"cultures","kind":"may","note":"Dairy cultures may carry milk."},
{"parent":"milk","term":"Lactic acid","norm":"lactic acid","kind":"may","note":"Usually fermented from sugar; occasionally dairy. Verify."},
{"parent":"soy","term":"Hydrolyzed vegetable protein","norm":"hydrolyzed vegetable protein","kind":"may","note":"HVP is commonly soy-derived."},
{"parent":"wheat","term":"Hydrolyzed vegetable protein","norm":"hydrolyzed vegetable protein","kind":"may","note":"HVP can be wheat-derived."},
{"parent":"milk","term":"Paneer","norm":"paneer","kind":"contains","note":"Fresh curdled-milk cheese."},
{"parent":"soy","term":"Gochujang","norm":"gochujang","kind":"may","note":"Korean chili paste; fermented soybean."},
{"parent":"wheat","term":"Gochujang","norm":"gochujang","kind":"may","note":"Often contains wheat/barley."},
{"parent":"sesame","term":"Furikake","norm":"furikake","kind":"may","note":"Japanese rice seasoning; usually sesame."},
{"parent":"fish","term":"Furikake","norm":"furikake","kind":"may","note":"Often contains bonito (fish)."},
{"parent":"egg","term":"Nougat","norm":"nougat","kind":"may","note":"Typically whipped egg white."},
{"parent":"almond","term":"Nougat","norm":"nougat","kind":"may","note":"Often contains almonds/other nuts."},
{"parent":"fish","term":"Kimchi","norm":"kimchi","kind":"may","note":"Often made with fish sauce."},
{"parent":"crustacean","term":"Kimchi","norm":"kimchi","kind":"may","note":"Often made with salted shrimp."},
{"parent":"soy","term":"Doenjang","norm":"doenjang","kind":"may","note":"Korean soybean paste."},
{"parent":"soy","term":"Hoisin","norm":"hoisin","kind":"may","note":"Usually fermented soybean."},
{"parent":"wheat","term":"Seitan","norm":"seitan","kind":"contains","note":"Wheat gluten (also in seed_02)."}],
  subGroups: [{"id":"allergen.milk","label":"Milk and Dairy","domain":"ALLERGEN"},
{"id":"allergen.egg","label":"Eggs","domain":"ALLERGEN"},
{"id":"allergen.wheat","label":"Wheat","domain":"ALLERGEN"},
{"id":"allergen.soy","label":"Soybeans","domain":"ALLERGEN"},
{"id":"allergen.peanut","label":"Peanuts","domain":"ALLERGEN"},
{"id":"allergen.treenut","label":"Tree Nuts","domain":"ALLERGEN"},
{"id":"allergen.fish","label":"Fish","domain":"ALLERGEN"},
{"id":"allergen.shellfish","label":"Shellfish","domain":"ALLERGEN"},
{"id":"allergen.sesame","label":"Sesame","domain":"ALLERGEN"},
{"id":"intol.lactose","label":"Lactose","domain":"INTOLERANCE"},
{"id":"intol.gluten","label":"Gluten","domain":"INTOLERANCE"},
{"id":"intol.fructose","label":"Fructose","domain":"INTOLERANCE"},
{"id":"intol.histamine","label":"Histamine","domain":"INTOLERANCE"},
{"id":"intol.sulfites","label":"Sulfites","domain":"INTOLERANCE"},
{"id":"intol.caffeine","label":"Caffeine","domain":"INTOLERANCE"},
{"id":"intol.sweeteners","label":"Artificial Sweeteners","domain":"INTOLERANCE"},
{"id":"intol.fodmaps","label":"FODMAPs","domain":"INTOLERANCE"}],
  opaque: [{"norm":"natural flavors","note":"May contain milk, soy, egg or others — source not declared."},
{"norm":"natural flavoring","note":"May contain undeclared allergens."},
{"norm":"artificial flavors","note":"May contain undeclared allergens."},
{"norm":"flavoring","note":"Unspecified; may hide allergens."},
{"norm":"flavor","note":"Unspecified; may hide allergens."},
{"norm":"spices","note":"Unspecified blend; may hide allergens (e.g. sesame, mustard)."},
{"norm":"spice","note":"Unspecified; may hide allergens."},
{"norm":"seasoning","note":"Unspecified blend; may hide allergens."},
{"norm":"seasoning blend","note":"Composite; may contain soy, wheat, milk, sesame."},
{"norm":"spice extract","note":"Unspecified; may hide allergens."},
{"norm":"vegetable oil","note":"Unspecified oil; could include peanut/soy/sesame."},
{"norm":"vegetable broth","note":"Composite; may contain undeclared allergens."},
{"norm":"hydrolyzed vegetable protein","note":"Commonly soy- or wheat-derived; source not always declared."},
{"norm":"hydrolyzed plant protein","note":"Commonly soy- or wheat-derived."},
{"norm":"modified food starch","note":"Source grain not always declared (may be wheat)."},
{"norm":"starch","note":"Unspecified source (may be wheat)."},
{"norm":"emulsifier","note":"Unspecified; may be soy/egg lecithin or animal-derived."},
{"norm":"enzymes","note":"Unspecified; may carry milk in dairy contexts."},
{"norm":"cultures","note":"Unspecified; may carry milk."}]
};
